### ISSUE TITLE
Use of GetLastError is subject to race conditions

### ISSUE THREAD

**Issue by jaraco** [enthought/pywin32-ctypes#122]
In https://github.com/python/cpython/issues/105914#issuecomment-1603649554, @eryksun had this advice:

> The use of `ctypes.GetLastError()` in "win32ctypes/core/ctypes/_util.py" is dubious. In general, WinAPI function prototypes should use `use_last_error=True`. It can be configured on `ctypes.WinDLL` instances or on individual `ctypes.WINFUNCTYPE()` prototypes. This setting causes the thread's last error value to be saved to a thread-local value in C, immediately after the FFI call, before any other Python runtime or Python code can be called. Code can get and set the thread-local value via `ctypes.get_last_error()` and `ctypes.set_last_error()`, and raise a formatted `OSError` exception via `raise ctypes.WinError(ctypes.get_last_error())`.

**Comment by itziakos** [comment]
Thanks @jaraco, I will have a look.
