### ISSUE TITLE
v0.2.3 not published to pypi

### ISSUE THREAD

**Issue by altendky** [enthought/pywin32-ctypes#136]
It looks like [v0.2.3](https://github.com/enthought/pywin32-ctypes/commit/30d3d1345d22a0a1ccab86ceae5d25e438897077) didn't make it to PyPI.  Nor GitHub https://github.com/enthought/pywin32-ctypes/releases.

https://pypi.org/project/pywin32-ctypes/#history
![image](https://github.com/user-attachments/assets/6c2342ea-2c6e-45e6-8e86-4d2c63a0d466)

**Comment by itziakos** [comment]
I will upload a new wheel this week. Sorry I neglected to do this earlier.

**Comment by itziakos** [comment]
pywin32-ctypes 0.2.3 has been released on PyPI

**Comment by altendky** [comment]
Thanks!
