### ISSUE TITLE
Drop-in replacement 

### ISSUE THREAD

**Issue by stopiccot** [enthought/pywin32-ctypes#16]
Can pywin32-ctypes run as a drop-in replacement for pywin32 so 

```
import win32api
```

just works without modifying any code?

**Comment by virtuald** [comment]
What is the harm in conflicting with pywin32? Presumably one wouldn't install them side-by-side?

**Comment by cournape** [comment]
> What is the harm in conflicting with pywin32? Presumably one wouldn't install them side-by-side?

There are multiple reasons:

1. it is rude to "overload" an existing namespace
2. you actually can't control whether both pywin32/pywin32-ctypes will be installed together or not. Say you develop your own program that depends on pywin32-ctypes but somebody else installs a library that depends on pywin32.
3. once we have a usable core of routines in place, we intend to build a better API, as the pywin32 API is too low-level
