### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by virtuald** [enthought/pywin32-ctypes#45]
We have some additional APIs to add, and would like to see a new release on pypi. However, if this is dead, we'll just fork it and push to pypi ourselves. Let me know, thanks!

**Comment by itziakos** [comment]
The project is not dead but it is progressing slowly. I can have a new release by the end of this week.

**Comment by virtuald** [comment]
I would like to see a release include the new APIs from the PR I just filed, so we can use this with pyinstaller. If there's a release, then we can push some changes to pyinstaller to have this repo as a possible dependency if pywin32 isn't available (such as in an msys environment).

**Comment by itziakos** [comment]
Thanks for the PR @virtuald, I will get a release out by the end of the week.
