### ISSUE TITLE
pywin32-ctypes 0.1.0 fails to install on Windows

### ISSUE THREAD

**Issue by silvana-i** [enthought/pywin32-ctypes#60]
We are using latest Python 2.7, and pip fails to install pywin32-ctypes with this error:

> Collecting pywin32-ctypes; sys_platform == "win32" (from keyring==10.2->-r 
> requirements.txt (line 12))
>   Using cached pywin32-ctypes-0.1.0.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "c:\users\admini\~1\appdata\local\temp\pip-build-qwyflc\pywin32-
> ctypes\setup.py", line 7, in <module>
>         os.path.join(HERE, 'VERSION')).read().strip()
>     IOError: [Errno 2] No such file or directory: 
> 'c:\\users\\admini~1\\appdata\\local\\temp\\pip-build-qwyflc\\pywin32-
> ctypes\\VERSION'
> 
> ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in 
> c:\users\admini~1\appdata\local\temp\pip-build-qwyflc\pywin32-ctypes\

**Comment by lmazuel** [comment]
Same here

**Comment by andscho-msft** [comment]
### Workaround

Just (temporarily) add this line to your requirements.txt

```
pywin32-ctypes == 0.0.1
```

**Comment by silvana-i** [comment]
Yes, we did this, but it is just a workaround. I don't want to have different conditions for the different platforms. We use Linux and Windows environments.

**Comment by MinchinWeb** [comment]
Ran into the same thing. I think the issue is that `VERSION` file was moved from the `win32ctypes` to the project root, but the `MANIFEST.in` file wasn't updated. This results in the `VERSION` being missing from the source distribution on PyPI, causing installation to fail as `setup.py` refers to the `VERSION` file.

**Comment by itziakos** [comment]
sorry for this my bad. I will make an updated release

**Comment by itziakos** [comment]
Just made a bugfix release 0.1.1 (https://pypi.python.org/pypi)

**Comment by MinchinWeb** [comment]
The new version installs without issue. Thanks for the quick response!
