### ISSUE TITLE
win32ctypes.pywintypes missing in 0.1.0

### ISSUE THREAD

**Issue by jaraco** [enthought/pywin32-ctypes#64]
In jaraco/keyring#278, it appears that the changes in pywin32-ctypes 0.1.0 introduced backward-incompatible changes that cause the win32cred and/or pywintypes not to import properly, causing keyring to stop working on Windows.

More investigation is needed.

**Comment by jaraco** [comment]
Indeed, it seems the issue is that the modules that were formerly available are no longer available:

```
PS C:\WINDOWS\system32> rwt pywin32-ctypes
Collecting pywin32-ctypes
  Downloading pywin32-ctypes-0.1.1.tar.gz
Installing collected packages: pywin32-ctypes
  Running setup.py install for pywin32-ctypes ... done
Successfully installed pywin32-ctypes-0.1.1
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import win32cred
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'win32cred'
>>> import pywintypes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pywintypes'
```

**Comment by jaraco** [comment]
It looks like a compatibility layer was added for `win32api` and `win32cred`, but not for `win32ctypes.pywintypes`.

**Comment by jaraco** [comment]
Thanks!

**Comment by itziakos** [comment]
No problem, sorry for the mistake, will make a new bugfix release soon
